#!/bin/bash
set -e

# CDDA linux build script
# CHANGE USER SETTINGS BEFORE USE!

VERSION=1.3.0

########################################
#          USER SETTINGS               #
########################################

remote_source_url="https://github.com/CleverRaven/Cataclysm-DDA.git"          # cdda source git repo url
git_dir="/mnt/hd/me/git_local"                                        # local git repos dir
gitrev='HEAD'                                                        # option: [ HEAD, commit,tag ]  build which revision. default: HEAD;  use commit or tag
lang="zh_CN"                                                        # choose language

bCheckDependencies=0                # should always set to 0. fedora only. use dnf check dependencies

bPause=1                            # default: 1;  1: pause scritp after function, see terminal output; 0: no pause, build until success or fail
bUpdate=1                            # should always set to 1: pull updates from remote; 0: skip check update
bUpdateTilesets=1                    # should always set to 1: download tilesets; 0: skip
bPatch=0                            # default: 0;  0: don't use custom patches; 1: use some custom patches
patch_dir="$git_dir/$local-patch"    # put your custom patches in this dir

ts="$(date +%Y%m%d_%H%M%S)"
install_dir="/mnt/hd/me/tmp/$ts/Cataclysm-DDA"        #install to this dir

git_user_email='user@e.mail'        # set git config user.mail
git_user_name='username'        # set git config user.name

march_native=1                # add -march=native to Makefile. maybe optimize for ONLY your building CPU
pipe=1                      # add -pipe to Makefile. build faster
disable_crater=1                # disable crater, i do not like it

iJobNum=$(($(nproc)))

# https://github.com/CleverRaven/Cataclysm-DDA/blob/master/doc/COMPILING/COMPILING.md
## Makefile flags
# CLANG do not work with MOLD or GOLD option
makeflags=(-j"$iJobNum"\
    CLANG=0\
    CCACHE=1\
    RELEASE=1\
    MOLD=0\
    LTO=0\
    TILES=1\
    SOUND=1\
    LANGUAGES="$lang"\
    TESTS=0\
    RUNTESTS=0\
    )
    #PCH=0\

#download tilesets you use from https://github.com/I-am-Erk/CDDA-Tilesets/releases
tileset=(Altica.zip ChibiUltica.zip MshockXotto+.zip Ultica_iso.zip UltimateCataclysm.zip)

########################################
#         end of USER SETTINGS         #
########################################

# Paus or not pause
clbs_pause()
{
    if (( bPause == 1 )); then
        read -r -p 'Press Ctrl+C to terminate, press any key to continue...'
    fi
}

clbs_check_dependencies()
{
    dependencies=('@C Development Tools and Libraries' git ncurses-devel astyle-devel SDL2-devel SDL2_image-devel SDL2_mixer-devel SDL2_ttf-devel)
    if { dnf list --available "${dependencies[@]}" 2>/dev/null; }; then
        read -r -p 'Install dependencies? [y/n]'
        case "$REPLY" in
            y|Y)
                sudo dnf install "${dependencies[@]}"
                ;;
            *)
                printf 'User abort.\n'
                exit 1
                ;;
        esac
    fi
    clbs_pause
}

#clean build branch and files
f_clean()
{
    git stash
    git checkout master
    if git branch -D my_custom_build; then :; fi
    git clean -fdx
    git restore .
}

#usage: clbs_update git_url
clbs_update()
{
    [ -d "$git_dir" ] || mkdir -p "$git_dir"
    cd "$git_dir" || exit 1

    local="$(echo "$1" | sed -E 's|^.*/||g; s|\..*$||g')"

    if [ -d ./"$local"/.git ]; then
        cd ./"$local"
        f_clean
        if (( bUpdate == 1 )); then
            git pull
        else
            printf '%s update skipped.\n' "$1"
        fi
    else
        git clone "$1" "$local"
        cd ./"$local"
    fi

    printf '[INFO] Update source end.\n'
    clbs_pause
}

# version, build in git dir
clbs_version()
{
    build_rev="$(git log -1 --pretty='format:%H %(describe:tags=true)' "$gitrev") "
    [ -n "$build_rev" ] || { printf '[ERROR] {%s}: gitrevision gitrev=%s not found.\n' "${FUNCNAME[0]}" "$gitrev"; exit 1; }
    mkdir -p "$install_dir"
    printf '%s\n' "$build_rev" > "$install_dir"/version.txt
    gitcfg=0
}

# git config once
f_git_config()
{
    if (( gitcfg == 0 )); then
        git config user.email "$git_user_email"
        git config user.name "$git_user_name"
        gitcfg=1
    fi
}

# create custom build branch once
f_build_branch()
{
    f_git_config
    if (( gitcfg == 1 )); then
        git checkout -b my_custom_build
        gitcfg=2
    fi
}

f_mod_makefile()
{
    f_build_branch
    if (( pipe == 1 && march_native ==1 )); then
        sed -Ei 's/ *# OTHERS \+= -march=native.*/  OTHERS \+= -march=native -pipe/' Makefile
        git commit -a -m 'Add build option: -march=native -pipe'
    elif (( pipe == 1 && march_native ==0 )); then
        sed -Ei 's/ *# OTHERS \+= -march=native.*/  OTHERS \+= -pipe/' Makefile
        git commit -a -m 'Add build option: -pipe'
    elif (( pipe == 0 && march_native ==1 )); then
        sed -Ei 's/ *# OTHERS \+= -march=native.*/  OTHERS \+= -march=native/' Makefile
        git commit -a -m 'Add build option: -march=native'
    fi
    clbs_pause
}

f_disable_crater()
{
    f_build_branch
    sed -Ei 's/"occurrences": \[ 66, 100 \]/"occurrences": \[ 0, 0 \]/' data/json/overmap/overmap_mutable/crater.json
    #sed -Ei 's/"check_for_locations_area": \[ \{ "type": \[ "land", "road", "agricultural" \]/"check_for_locations_area": \[ \{ "type": \[  \]/' data/json/overmap/overmap_mutable/crater.json
    sed -Ei 's/"mx_crater": [0-9]+/"mx_crater": 0/g' data/json/region_settings/region_settings/regional_map_settings.json
    git commit -a -m 'Disable crater'
    #clbs_pause
}

# apply custom patch
clbs_patch()
{
    for p in "$1"/*; do
        [ -e "$p" ] || continue
        git apply --verbose "$p"
    done
    clbs_pause
}

# make, work in "$build_dir"
clbs_build()
{
    time_start=$(date '+%T')
    make "${makeflags[@]}"
}

f_install_tilesets()
{
    #example dwonload link:  https://github.com/I-am-Erk/CDDA-Tilesets/releases/download/2025-01-05/Altica.zip
    tilesets_url='https://github.com/I-am-Erk/CDDA-Tilesets/releases'
    #get tilesets release date from github release page, generate download link, eg: 2025-01-05
    trdate="$(curl -s "$tilesets_url" | grep -E -m 1 "Tilesets Release [0-9]{4}-[0-9]{2}-[0-9]{2}" | sed -E 's|^.*Tilesets Release ||g; s|<\/h2>||g')"
    [ -n "$trdate" ] || { printf "[ERROR] get tilesets release date failed. \$trdate=%s" "$trdate"; exit 1; }

    cd "$git_dir"
    mkdir -p "$trdate"
    cd "$trdate"
    declare -i i
    for (( i=${#tileset[@]}; i--; )); do
        #echo ${tileset[i]}
        curl -JLO "$tilesets_url/download/$trdate/${tileset[i]}"
    done

    for f in ./*.zip; do
        unzip "$f"
    done

    cp -R ./*/ "$install_dir"/gfx
}

# replace `make install`
clbs_install()
{
    printf '[INFO] Installing to %s\n' "$install_dir"
    list=( data/core\
            data/font\
            data/json\
            data/mods\
            data/names\
            data/raw\
            data/motd\
            data/credits\
            data/title\
            data/fontdata.json )
    if [[ "${makeflags[*]}" =~ TILES=1 ]]; then list+=( gfx cataclysm-tiles zzip ); else list+=( cataclysm zzip ); fi
    if [[ "${makeflags[*]}" =~ SOUND=1 ]]; then list+=( data/sound ); fi
    if [[ "${makeflags[*]}" =~ LANGUAGES=.+ ]]; then list+=( lang/mo ); fi

    mapfile -t dir_list < <( printf '%s\n' "${list[@]}" | grep / | sed -E 's/\/[^/]*$//' | sort | uniq )
    for d in "${dir_list[@]}"; do mkdir -p "$install_dir"/"$d"; done
    for (( i=0 ; i < ${#list[@]} ; i++ )); do
        if [ -e "${list[i]}" ]; then
            cp -R "${list[i]}" "$install_dir"/"${list[i]}"
        else
            printf '[WARN] %s is missing!\n' "${list[i]}"
        fi
    done

    f_clean

    if (( bUpdateTilesets == 1 )); then f_install_tilesets; fi

    time_end=$( date '+%T' )
    printf '[INFO] Make end.\n'
    echo "build start: $time_start"
    echo "build end:   $time_end"
}

## main()
#{

printf 'CDDA linux build script %s\n\n    CHANGE USER SETTINGS BEFORE USE!    \n\n' "$VERSION"
printf 'Make flags:\n'
printf '    %s\n' "${makeflags[@]}"
printf '\n'


(( march_native == 1 )) && printf '    -march=native\n'
(( pipe == 1)) && printf '    -pipe\n'
(( disable_crater == 1 )) && printf '    disable crater\n'

printf 'Start building %s?\n\n' "$gitrev"
clbs_pause

if (( bCheckDependencies == 1 )); then clbs_check_dependencies; fi


clbs_update "$remote_source_url"
clbs_version
if (( march_native == 1 || pipe == 1)); then f_mod_makefile; fi
if (( bPatch == 1 )); then clbs_patch "$patch_dir"; fi
clbs_build
if (( disable_crater == 1 )); then f_disable_crater; fi

clbs_install

#}
